---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sds-node-configurator
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-node-configurator")) | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: sds-node-configurator
  template:
    metadata:
      name: sds-node-configurator
      namespace: d8-{{ .Chart.Name }}
      {{- include "helm_lib_module_labels" (list . (dict "app" "sds-node-configurator")) | nindent 6 }}
    spec:
      {{- include "helm_lib_priority_class" (tuple . "cluster-medium") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "any-node" "storage-problems") | nindent 6 }}
      nodeSelector:
        storage.deckhouse.io/sds-drbd-node: ""
      imagePullSecrets:
        - name: {{ .Chart.Name }}-module-registry
      serviceAccountName: sds-node-configurator
      containers:
      - name: sds-node-configurator-agent
        image: {{ include "helm_lib_module_image" (list . "agent") }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          seLinuxOptions:
            level: s0
            type: spc_t
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: host-device-dir
          mountPath: /dev/
        - name: modules-dir
          mountPath: /lib/modules
        - name: host-sys-dir
          mountPath: /sys/
        - name: host-root
          mountPath: /host-root/
          mountPropagation: HostToContainer
      volumes:
      - name: host-device-dir
        hostPath:
          path: /dev
          type: ""
      - name: host-sys-dir
        hostPath:
          path: /sys/
          type: Directory
      - name: host-root
        hostPath:
          path: /
      - name: modules-dir
        hostPath:
          path: /lib/modules/
          type: DirectoryOrCreate

