{{- if (.Values.global.enabledModules | has "operator-prometheus-crd") }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sds-node-configurator-agent
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list $ (dict "prometheus" "main")) | nindent 2 }}
spec:
  podMetricsEndpoints:
  - port: 4202
    scheme: https
    path: /metrics
    bearerTokenSecret:
      name: "prometheus-token"
      key: "token"
    tlsConfig:
      insecureSkipVerify: true
    honorLabels: true
    scrapeTimeout: {{ include "helm_lib_prometheus_target_scrape_timeout_seconds" (list $ 25) }}
    relabelings:
    - regex: endpoint|namespace|pod|container
      action: labeldrop
    - targetLabel: job
      replacement: sds-node-configurator-agent
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - targetLabel: tier
      replacement: cluster
    - sourceLabels: [__meta_kubernetes_pod_ready]
      regex: "true"
      action: keep
  selector:
    matchLabels:
      app: sds-node-configurator
  namespaceSelector:
    matchNames:
    - d8-{{ .Chart.Name }}
{{- end }}
