apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-configurator
  namespace: d8-storage-configurator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-configurator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - blockdevices
    verbs:
      - get
      - list
      - create
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-configurator
subjects:
  - kind: ServiceAccount
    name: storage-configurator
    namespace: d8-storage-configurator
roleRef:
  kind: ClusterRole
  name: storage-configurator
  apiGroup: rbac.authorization.k8s.io
