apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:sds-node-configurator
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - blockdevices
      - lvmvolumegroups
      - lvmvolumegroups/status
      - lvmlogicalvolumes
      - lvmlogicalvolumes/status
      - lvmlogicalvolumesnapshots
      - lvmlogicalvolumesnapshots/status
      - localstorageclasses
      - replicatedstorageclasses
    verbs:
      - get
      - list
      - create
      - delete
      - watch
      - update
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - update
      - list
      - delete
      - patch
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - blockdevicefilters
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:sds-node-configurator
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:sds-node-configurator
  apiGroup: rbac.authorization.k8s.io
