apiVersion: v1
kind: ServiceAccount
metadata:
  name: sds-node-configurator
  namespace: d8-{{ .Chart.Name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:sds-node-configurator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - list
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - blockdevices
      - lvmvolumegroups
      - lvmvolumegroups/status
      - lvmlogicalvolumes
      - lvmlogicalvolumes/status
      - lvmlogicalvolumesnapshots
      - lvmlogicalvolumesnapshots/status
    verbs:
      - get
      - list
      - create
      - delete
      - watch
      - update
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - update
      - list
      - delete
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: d8:{{ .Chart.Name }}:sds-node-configurator
subjects:
  - kind: ServiceAccount
    name: sds-node-configurator
    namespace: d8-{{ .Chart.Name }}
roleRef:
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:sds-node-configurator
  apiGroup: rbac.authorization.k8s.io
