{{- if not .Values.sdsNodeConfigurator.disableDs }}
---
apiVersion: v1
kind: Service
metadata:
  name: sds-node-configurator-agent
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "sds-node-configurator")) | nindent 2 }}
spec:
  selector:
    app: sds-node-configurator
  ports:
  - name: metrics
    port: 4202
    targetPort: 4202
    protocol: TCP
  type: ClusterIP
{{- end }}
