apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    heritage: deckhouse
    module: sds-node-configurator
    rbac.deckhouse.io/aggregate-to-storage-as: viewer
    rbac.deckhouse.io/kind: manage
    rbac.deckhouse.io/level: module
    rbac.deckhouse.io/namespace: d8-sds-node-configurator
  name: d8:manage:permission:module:sds-node-configurator:view
rules:
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - blockdevices
      - lvmvolumegroups
      - lvmvolumegroupsets
      - lvmvolumegroupbackups
      - lvmlogicalvolumes
      - lvmlogicalvolumesnapshots
    verbs:
      - get
      - list
      - watch
