linters-settings:
  containter:
    exclude-rules:
      no-new-privileges:
        - kind: DaemonSet
          name: sds-node-configurator
          container: sds-node-configurator-agent
        - kind: DaemonSet
          name: sds-node-configurator
          container: thin-volumes-enabler
  module:
    oss:
      disable: true
  openapi:
    exclude-rules:
      enum:
        - spec.versions[0].schema.openAPIV3Schema.properties.status.properties.fsType
