run:
  timeout: 10m

issues:
  exclude:
    - ST1005.*
    - "should not use dot imports"
    - "don't use an underscore in package name"
    - "exported: .*"
    - "could not import"

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/deckhouse)

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - gci
    - gocritic
    - gofmt
    #  - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    #  - structcheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - copyloopvar
