{{- if and (not (eq "dev" .Values.global.deckhouseVersion)) (semverCompare "<1.64" .Values.global.deckhouseVersion) }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "d8-{{ .Chart.Name }}-sc-validation"
webhooks:
  - name: "d8-{{ .Chart.Name }}-sc-validation.deckhouse.io"
    rules:
      - apiGroups: ["storage.deckhouse.io"]
        apiVersions: ["v1alpha1"]
        operations: ["*"]
        resources: ["lvmlogicalvolumesnapshots"]
        scope: "Cluster"
    clientConfig:
      service:
        namespace: "d8-{{ .Chart.Name }}"
        name: "webhooks"
        path: "/llvs-validate"
      caBundle: |
        {{ .Values.sdsLocalVolume.internal.customWebhookCert.ca }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
