// Copyright 2026 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: commands.go
//
// Generated by this command:
//
//	mockgen -copyright_file ../../../../hack/boilerplate.mockgen.txt -write_source_comment -destination=../mock_utils/commands.go -source=commands.go
//

// Package mock_utils is a generated GoMock package.
package mock_utils

import (
	bytes "bytes"
	context "context"
	reflect "reflect"
	time "time"

	internal "github.com/deckhouse/sds-node-configurator/images/agent/internal"
	logger "github.com/deckhouse/sds-node-configurator/images/agent/internal/logger"
	monitoring "github.com/deckhouse/sds-node-configurator/images/agent/internal/monitoring"
	utils "github.com/deckhouse/sds-node-configurator/images/agent/internal/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockCommands is a mock of Commands interface.
type MockCommands struct {
	ctrl     *gomock.Controller
	recorder *MockCommandsMockRecorder
	isgomock struct{}
}

// MockCommandsMockRecorder is the mock recorder for MockCommands.
type MockCommandsMockRecorder struct {
	mock *MockCommands
}

// NewMockCommands creates a new mock instance.
func NewMockCommands(ctrl *gomock.Controller) *MockCommands {
	mock := &MockCommands{ctrl: ctrl}
	mock.recorder = &MockCommandsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommands) EXPECT() *MockCommandsMockRecorder {
	return m.recorder
}

// CreateFileDevice mocks base method.
func (m *MockCommands) CreateFileDevice(ctx context.Context, path string, sizeBytes int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFileDevice", ctx, path, sizeBytes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFileDevice indicates an expected call of CreateFileDevice.
func (mr *MockCommandsMockRecorder) CreateFileDevice(ctx, path, sizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFileDevice", reflect.TypeOf((*MockCommands)(nil).CreateFileDevice), ctx, path, sizeBytes)
}

// CreateLVShared mocks base method.
func (m *MockCommands) CreateLVShared(ctx context.Context, vgName, lvName, size string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLVShared", ctx, vgName, lvName, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLVShared indicates an expected call of CreateLVShared.
func (mr *MockCommandsMockRecorder) CreateLVShared(ctx, vgName, lvName, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLVShared", reflect.TypeOf((*MockCommands)(nil).CreateLVShared), ctx, vgName, lvName, size)
}

// CreatePV mocks base method.
func (m *MockCommands) CreatePV(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePV", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePV indicates an expected call of CreatePV.
func (mr *MockCommandsMockRecorder) CreatePV(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePV", reflect.TypeOf((*MockCommands)(nil).CreatePV), ctx, path)
}

// CreateThickLogicalVolume mocks base method.
func (m *MockCommands) CreateThickLogicalVolume(vgName, lvName string, size int64, contiguous bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThickLogicalVolume", vgName, lvName, size, contiguous)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThickLogicalVolume indicates an expected call of CreateThickLogicalVolume.
func (mr *MockCommandsMockRecorder) CreateThickLogicalVolume(vgName, lvName, size, contiguous any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThickLogicalVolume", reflect.TypeOf((*MockCommands)(nil).CreateThickLogicalVolume), vgName, lvName, size, contiguous)
}

// CreateThinLogicalVolume mocks base method.
func (m *MockCommands) CreateThinLogicalVolume(vgName, tpName, lvName string, size int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThinLogicalVolume", vgName, tpName, lvName, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThinLogicalVolume indicates an expected call of CreateThinLogicalVolume.
func (mr *MockCommandsMockRecorder) CreateThinLogicalVolume(vgName, tpName, lvName, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThinLogicalVolume", reflect.TypeOf((*MockCommands)(nil).CreateThinLogicalVolume), vgName, tpName, lvName, size)
}

// CreateThinLogicalVolumeFromSource mocks base method.
func (m *MockCommands) CreateThinLogicalVolumeFromSource(name, sourceVgName, sourceName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThinLogicalVolumeFromSource", name, sourceVgName, sourceName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThinLogicalVolumeFromSource indicates an expected call of CreateThinLogicalVolumeFromSource.
func (mr *MockCommandsMockRecorder) CreateThinLogicalVolumeFromSource(name, sourceVgName, sourceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThinLogicalVolumeFromSource", reflect.TypeOf((*MockCommands)(nil).CreateThinLogicalVolumeFromSource), name, sourceVgName, sourceName)
}

// CreateThinLogicalVolumeSnapshot mocks base method.
func (m *MockCommands) CreateThinLogicalVolumeSnapshot(name, sourceVgName, sourceName string, tags []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThinLogicalVolumeSnapshot", name, sourceVgName, sourceName, tags)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThinLogicalVolumeSnapshot indicates an expected call of CreateThinLogicalVolumeSnapshot.
func (mr *MockCommandsMockRecorder) CreateThinLogicalVolumeSnapshot(name, sourceVgName, sourceName, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThinLogicalVolumeSnapshot", reflect.TypeOf((*MockCommands)(nil).CreateThinLogicalVolumeSnapshot), name, sourceVgName, sourceName, tags)
}

// CreateThinPool mocks base method.
func (m *MockCommands) CreateThinPool(thinPoolName, vgName string, size int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThinPool", thinPoolName, vgName, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThinPool indicates an expected call of CreateThinPool.
func (mr *MockCommandsMockRecorder) CreateThinPool(thinPoolName, vgName, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThinPool", reflect.TypeOf((*MockCommands)(nil).CreateThinPool), thinPoolName, vgName, size)
}

// CreateThinPoolFullVGSpace mocks base method.
func (m *MockCommands) CreateThinPoolFullVGSpace(thinPoolName, vgName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThinPoolFullVGSpace", thinPoolName, vgName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThinPoolFullVGSpace indicates an expected call of CreateThinPoolFullVGSpace.
func (mr *MockCommandsMockRecorder) CreateThinPoolFullVGSpace(thinPoolName, vgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThinPoolFullVGSpace", reflect.TypeOf((*MockCommands)(nil).CreateThinPoolFullVGSpace), thinPoolName, vgName)
}

// CreateVGLocal mocks base method.
func (m *MockCommands) CreateVGLocal(vgName, lvmVolumeGroupName string, pvNames []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVGLocal", vgName, lvmVolumeGroupName, pvNames)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVGLocal indicates an expected call of CreateVGLocal.
func (mr *MockCommandsMockRecorder) CreateVGLocal(vgName, lvmVolumeGroupName, pvNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVGLocal", reflect.TypeOf((*MockCommands)(nil).CreateVGLocal), vgName, lvmVolumeGroupName, pvNames)
}

// CreateVGShared mocks base method.
func (m *MockCommands) CreateVGShared(ctx context.Context, params utils.SharedVGParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVGShared", ctx, params)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVGShared indicates an expected call of CreateVGShared.
func (mr *MockCommandsMockRecorder) CreateVGShared(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVGShared", reflect.TypeOf((*MockCommands)(nil).CreateVGShared), ctx, params)
}

// DetachLoopDevice mocks base method.
func (m *MockCommands) DetachLoopDevice(ctx context.Context, loopDev string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachLoopDevice", ctx, loopDev)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetachLoopDevice indicates an expected call of DetachLoopDevice.
func (mr *MockCommandsMockRecorder) DetachLoopDevice(ctx, loopDev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachLoopDevice", reflect.TypeOf((*MockCommands)(nil).DetachLoopDevice), ctx, loopDev)
}

// EnsureFileDeviceDirectory mocks base method.
func (m *MockCommands) EnsureFileDeviceDirectory(ctx context.Context, directory string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureFileDeviceDirectory", ctx, directory)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureFileDeviceDirectory indicates an expected call of EnsureFileDeviceDirectory.
func (mr *MockCommandsMockRecorder) EnsureFileDeviceDirectory(ctx, directory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureFileDeviceDirectory", reflect.TypeOf((*MockCommands)(nil).EnsureFileDeviceDirectory), ctx, directory)
}

// ExtendLV mocks base method.
func (m *MockCommands) ExtendLV(size int64, vgName, lvName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendLV", size, vgName, lvName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtendLV indicates an expected call of ExtendLV.
func (mr *MockCommandsMockRecorder) ExtendLV(size, vgName, lvName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendLV", reflect.TypeOf((*MockCommands)(nil).ExtendLV), size, vgName, lvName)
}

// ExtendLVFullVGSpace mocks base method.
func (m *MockCommands) ExtendLVFullVGSpace(vgName, lvName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendLVFullVGSpace", vgName, lvName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtendLVFullVGSpace indicates an expected call of ExtendLVFullVGSpace.
func (mr *MockCommandsMockRecorder) ExtendLVFullVGSpace(vgName, lvName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendLVFullVGSpace", reflect.TypeOf((*MockCommands)(nil).ExtendLVFullVGSpace), vgName, lvName)
}

// ExtendVG mocks base method.
func (m *MockCommands) ExtendVG(vgName string, paths []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendVG", vgName, paths)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtendVG indicates an expected call of ExtendVG.
func (mr *MockCommandsMockRecorder) ExtendVG(vgName, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendVG", reflect.TypeOf((*MockCommands)(nil).ExtendVG), vgName, paths)
}

// FindLoopDeviceByFile mocks base method.
func (m *MockCommands) FindLoopDeviceByFile(ctx context.Context, filePath string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLoopDeviceByFile", ctx, filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindLoopDeviceByFile indicates an expected call of FindLoopDeviceByFile.
func (mr *MockCommandsMockRecorder) FindLoopDeviceByFile(ctx, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLoopDeviceByFile", reflect.TypeOf((*MockCommands)(nil).FindLoopDeviceByFile), ctx, filePath)
}

// GetAllLVs mocks base method.
func (m *MockCommands) GetAllLVs(ctx context.Context) ([]internal.LVData, string, bytes.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLVs", ctx)
	ret0, _ := ret[0].([]internal.LVData)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bytes.Buffer)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetAllLVs indicates an expected call of GetAllLVs.
func (mr *MockCommandsMockRecorder) GetAllLVs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLVs", reflect.TypeOf((*MockCommands)(nil).GetAllLVs), ctx)
}

// GetAllPVs mocks base method.
func (m *MockCommands) GetAllPVs(ctx context.Context) ([]internal.PVData, string, bytes.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPVs", ctx)
	ret0, _ := ret[0].([]internal.PVData)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bytes.Buffer)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetAllPVs indicates an expected call of GetAllPVs.
func (mr *MockCommandsMockRecorder) GetAllPVs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPVs", reflect.TypeOf((*MockCommands)(nil).GetAllPVs), ctx)
}

// GetAllVGs mocks base method.
func (m *MockCommands) GetAllVGs(ctx context.Context) ([]internal.VGData, string, bytes.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllVGs", ctx)
	ret0, _ := ret[0].([]internal.VGData)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bytes.Buffer)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetAllVGs indicates an expected call of GetAllVGs.
func (mr *MockCommandsMockRecorder) GetAllVGs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllVGs", reflect.TypeOf((*MockCommands)(nil).GetAllVGs), ctx)
}

// GetBlockDevices mocks base method.
func (m *MockCommands) GetBlockDevices(ctx context.Context) ([]internal.Device, string, bytes.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockDevices", ctx)
	ret0, _ := ret[0].([]internal.Device)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bytes.Buffer)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetBlockDevices indicates an expected call of GetBlockDevices.
func (mr *MockCommandsMockRecorder) GetBlockDevices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockDevices", reflect.TypeOf((*MockCommands)(nil).GetBlockDevices), ctx)
}

// GetFileAllocatedBytes mocks base method.
func (m *MockCommands) GetFileAllocatedBytes(ctx context.Context, path string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileAllocatedBytes", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFileAllocatedBytes indicates an expected call of GetFileAllocatedBytes.
func (mr *MockCommandsMockRecorder) GetFileAllocatedBytes(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileAllocatedBytes", reflect.TypeOf((*MockCommands)(nil).GetFileAllocatedBytes), ctx, path)
}

// GetFilesystemSpace mocks base method.
func (m *MockCommands) GetFilesystemSpace(ctx context.Context, directory string) (string, internal.FilesystemSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesystemSpace", ctx, directory)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(internal.FilesystemSpace)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFilesystemSpace indicates an expected call of GetFilesystemSpace.
func (mr *MockCommandsMockRecorder) GetFilesystemSpace(ctx, directory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesystemSpace", reflect.TypeOf((*MockCommands)(nil).GetFilesystemSpace), ctx, directory)
}

// GetLV mocks base method.
func (m *MockCommands) GetLV(vgName, lvName string) (internal.LVData, string, bytes.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLV", vgName, lvName)
	ret0, _ := ret[0].(internal.LVData)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bytes.Buffer)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetLV indicates an expected call of GetLV.
func (mr *MockCommandsMockRecorder) GetLV(vgName, lvName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLV", reflect.TypeOf((*MockCommands)(nil).GetLV), vgName, lvName)
}

// GetLoopBackingFile mocks base method.
func (m *MockCommands) GetLoopBackingFile(ctx context.Context, loopDev string) (string, internal.LoopBackingFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoopBackingFile", ctx, loopDev)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(internal.LoopBackingFile)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLoopBackingFile indicates an expected call of GetLoopBackingFile.
func (mr *MockCommandsMockRecorder) GetLoopBackingFile(ctx, loopDev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoopBackingFile", reflect.TypeOf((*MockCommands)(nil).GetLoopBackingFile), ctx, loopDev)
}

// GetPV mocks base method.
func (m *MockCommands) GetPV(pvName string) (internal.PVData, string, bytes.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPV", pvName)
	ret0, _ := ret[0].(internal.PVData)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bytes.Buffer)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetPV indicates an expected call of GetPV.
func (mr *MockCommandsMockRecorder) GetPV(pvName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPV", reflect.TypeOf((*MockCommands)(nil).GetPV), pvName)
}

// GetVG mocks base method.
func (m *MockCommands) GetVG(vgName string) (internal.VGData, string, bytes.Buffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVG", vgName)
	ret0, _ := ret[0].(internal.VGData)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bytes.Buffer)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetVG indicates an expected call of GetVG.
func (mr *MockCommandsMockRecorder) GetVG(vgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVG", reflect.TypeOf((*MockCommands)(nil).GetVG), vgName)
}

// LVActivate mocks base method.
func (m *MockCommands) LVActivate(ctx context.Context, vgName, lvName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LVActivate", ctx, vgName, lvName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LVActivate indicates an expected call of LVActivate.
func (mr *MockCommandsMockRecorder) LVActivate(ctx, vgName, lvName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LVActivate", reflect.TypeOf((*MockCommands)(nil).LVActivate), ctx, vgName, lvName)
}

// LVActivateShared mocks base method.
func (m *MockCommands) LVActivateShared(ctx context.Context, vgName string, lvNames []string, shared bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LVActivateShared", ctx, vgName, lvNames, shared)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LVActivateShared indicates an expected call of LVActivateShared.
func (mr *MockCommandsMockRecorder) LVActivateShared(ctx, vgName, lvNames, shared any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LVActivateShared", reflect.TypeOf((*MockCommands)(nil).LVActivateShared), ctx, vgName, lvNames, shared)
}

// LVChangeDelTag mocks base method.
func (m *MockCommands) LVChangeDelTag(ctx context.Context, lv internal.LVData, tag string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LVChangeDelTag", ctx, lv, tag)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LVChangeDelTag indicates an expected call of LVChangeDelTag.
func (mr *MockCommandsMockRecorder) LVChangeDelTag(ctx, lv, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LVChangeDelTag", reflect.TypeOf((*MockCommands)(nil).LVChangeDelTag), ctx, lv, tag)
}

// LVDeactivateShared mocks base method.
func (m *MockCommands) LVDeactivateShared(ctx context.Context, vgName string, lvNames []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LVDeactivateShared", ctx, vgName, lvNames)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LVDeactivateShared indicates an expected call of LVDeactivateShared.
func (mr *MockCommandsMockRecorder) LVDeactivateShared(ctx, vgName, lvNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LVDeactivateShared", reflect.TypeOf((*MockCommands)(nil).LVDeactivateShared), ctx, vgName, lvNames)
}

// LVExtendShared mocks base method.
func (m *MockCommands) LVExtendShared(ctx context.Context, vgName, lvName, size string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LVExtendShared", ctx, vgName, lvName, size)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LVExtendShared indicates an expected call of LVExtendShared.
func (mr *MockCommandsMockRecorder) LVExtendShared(ctx, vgName, lvName, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LVExtendShared", reflect.TypeOf((*MockCommands)(nil).LVExtendShared), ctx, vgName, lvName, size)
}

// ListLoopDevices mocks base method.
func (m *MockCommands) ListLoopDevices(ctx context.Context) (string, []internal.LoopDeviceEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLoopDevices", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]internal.LoopDeviceEntry)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLoopDevices indicates an expected call of ListLoopDevices.
func (mr *MockCommandsMockRecorder) ListLoopDevices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLoopDevices", reflect.TypeOf((*MockCommands)(nil).ListLoopDevices), ctx)
}

// PVScan mocks base method.
func (m *MockCommands) PVScan(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PVScan", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PVScan indicates an expected call of PVScan.
func (mr *MockCommandsMockRecorder) PVScan(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PVScan", reflect.TypeOf((*MockCommands)(nil).PVScan), ctx)
}

// ReTag mocks base method.
func (m *MockCommands) ReTag(ctx context.Context, log logger.Logger, metrics *monitoring.Metrics, ctrlName string, cmdTimeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReTag", ctx, log, metrics, ctrlName, cmdTimeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReTag indicates an expected call of ReTag.
func (mr *MockCommandsMockRecorder) ReTag(ctx, log, metrics, ctrlName, cmdTimeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReTag", reflect.TypeOf((*MockCommands)(nil).ReTag), ctx, log, metrics, ctrlName, cmdTimeout)
}

// RemoveDMDevice mocks base method.
func (m *MockCommands) RemoveDMDevice(ctx context.Context, dmName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDMDevice", ctx, dmName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveDMDevice indicates an expected call of RemoveDMDevice.
func (mr *MockCommandsMockRecorder) RemoveDMDevice(ctx, dmName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDMDevice", reflect.TypeOf((*MockCommands)(nil).RemoveDMDevice), ctx, dmName)
}

// RemoveDMDeviceDeferred mocks base method.
func (m *MockCommands) RemoveDMDeviceDeferred(ctx context.Context, dmName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDMDeviceDeferred", ctx, dmName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveDMDeviceDeferred indicates an expected call of RemoveDMDeviceDeferred.
func (mr *MockCommandsMockRecorder) RemoveDMDeviceDeferred(ctx, dmName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDMDeviceDeferred", reflect.TypeOf((*MockCommands)(nil).RemoveDMDeviceDeferred), ctx, dmName)
}

// RemoveFileDevice mocks base method.
func (m *MockCommands) RemoveFileDevice(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFileDevice", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFileDevice indicates an expected call of RemoveFileDevice.
func (mr *MockCommandsMockRecorder) RemoveFileDevice(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFileDevice", reflect.TypeOf((*MockCommands)(nil).RemoveFileDevice), ctx, path)
}

// RemoveLV mocks base method.
func (m *MockCommands) RemoveLV(vgName, lvName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLV", vgName, lvName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveLV indicates an expected call of RemoveLV.
func (mr *MockCommandsMockRecorder) RemoveLV(vgName, lvName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLV", reflect.TypeOf((*MockCommands)(nil).RemoveLV), vgName, lvName)
}

// RemoveLVShared mocks base method.
func (m *MockCommands) RemoveLVShared(ctx context.Context, vgName, lvName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLVShared", ctx, vgName, lvName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveLVShared indicates an expected call of RemoveLVShared.
func (mr *MockCommandsMockRecorder) RemoveLVShared(ctx, vgName, lvName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLVShared", reflect.TypeOf((*MockCommands)(nil).RemoveLVShared), ctx, vgName, lvName)
}

// RemovePV mocks base method.
func (m *MockCommands) RemovePV(pvNames []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePV", pvNames)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePV indicates an expected call of RemovePV.
func (mr *MockCommandsMockRecorder) RemovePV(pvNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePV", reflect.TypeOf((*MockCommands)(nil).RemovePV), pvNames)
}

// RemoveVG mocks base method.
func (m *MockCommands) RemoveVG(vgName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveVG", vgName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveVG indicates an expected call of RemoveVG.
func (mr *MockCommandsMockRecorder) RemoveVG(vgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveVG", reflect.TypeOf((*MockCommands)(nil).RemoveVG), vgName)
}

// RemoveVGShared mocks base method.
func (m *MockCommands) RemoveVGShared(ctx context.Context, vgName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveVGShared", ctx, vgName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveVGShared indicates an expected call of RemoveVGShared.
func (mr *MockCommandsMockRecorder) RemoveVGShared(ctx, vgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveVGShared", reflect.TypeOf((*MockCommands)(nil).RemoveVGShared), ctx, vgName)
}

// ResizePV mocks base method.
func (m *MockCommands) ResizePV(ctx context.Context, pvName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizePV", ctx, pvName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResizePV indicates an expected call of ResizePV.
func (mr *MockCommandsMockRecorder) ResizePV(ctx, pvName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizePV", reflect.TypeOf((*MockCommands)(nil).ResizePV), ctx, pvName)
}

// SetLVTagShared mocks base method.
func (m *MockCommands) SetLVTagShared(ctx context.Context, vgName, lvName, tag string, add bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLVTagShared", ctx, vgName, lvName, tag, add)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetLVTagShared indicates an expected call of SetLVTagShared.
func (mr *MockCommandsMockRecorder) SetLVTagShared(ctx, vgName, lvName, tag, add any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLVTagShared", reflect.TypeOf((*MockCommands)(nil).SetLVTagShared), ctx, vgName, lvName, tag, add)
}

// SetLoopCapacity mocks base method.
func (m *MockCommands) SetLoopCapacity(ctx context.Context, loopDev string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLoopCapacity", ctx, loopDev)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetLoopCapacity indicates an expected call of SetLoopCapacity.
func (mr *MockCommandsMockRecorder) SetLoopCapacity(ctx, loopDev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLoopCapacity", reflect.TypeOf((*MockCommands)(nil).SetLoopCapacity), ctx, loopDev)
}

// SetLoopDirectIO mocks base method.
func (m *MockCommands) SetLoopDirectIO(ctx context.Context, loopDev string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLoopDirectIO", ctx, loopDev)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetLoopDirectIO indicates an expected call of SetLoopDirectIO.
func (mr *MockCommandsMockRecorder) SetLoopDirectIO(ctx, loopDev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLoopDirectIO", reflect.TypeOf((*MockCommands)(nil).SetLoopDirectIO), ctx, loopDev)
}

// SetupLoopDevice mocks base method.
func (m *MockCommands) SetupLoopDevice(ctx context.Context, filePath string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupLoopDevice", ctx, filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetupLoopDevice indicates an expected call of SetupLoopDevice.
func (mr *MockCommandsMockRecorder) SetupLoopDevice(ctx, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupLoopDevice", reflect.TypeOf((*MockCommands)(nil).SetupLoopDevice), ctx, filePath)
}

// UdevadmTrigger mocks base method.
func (m *MockCommands) UdevadmTrigger(ctx context.Context, paths []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UdevadmTrigger", ctx, paths)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UdevadmTrigger indicates an expected call of UdevadmTrigger.
func (mr *MockCommandsMockRecorder) UdevadmTrigger(ctx, paths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UdevadmTrigger", reflect.TypeOf((*MockCommands)(nil).UdevadmTrigger), ctx, paths)
}

// UnmarshalDevices mocks base method.
func (m *MockCommands) UnmarshalDevices(out []byte) ([]internal.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmarshalDevices", out)
	ret0, _ := ret[0].([]internal.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmarshalDevices indicates an expected call of UnmarshalDevices.
func (mr *MockCommandsMockRecorder) UnmarshalDevices(out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmarshalDevices", reflect.TypeOf((*MockCommands)(nil).UnmarshalDevices), out)
}

// VGActivate mocks base method.
func (m *MockCommands) VGActivate(ctx context.Context, vgName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VGActivate", ctx, vgName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VGActivate indicates an expected call of VGActivate.
func (mr *MockCommandsMockRecorder) VGActivate(ctx, vgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VGActivate", reflect.TypeOf((*MockCommands)(nil).VGActivate), ctx, vgName)
}

// VGChangeAddTag mocks base method.
func (m *MockCommands) VGChangeAddTag(ctx context.Context, vGName, tag string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VGChangeAddTag", ctx, vGName, tag)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VGChangeAddTag indicates an expected call of VGChangeAddTag.
func (mr *MockCommandsMockRecorder) VGChangeAddTag(ctx, vGName, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VGChangeAddTag", reflect.TypeOf((*MockCommands)(nil).VGChangeAddTag), ctx, vGName, tag)
}

// VGChangeDelTag mocks base method.
func (m *MockCommands) VGChangeDelTag(ctx context.Context, vGName, tag string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VGChangeDelTag", ctx, vGName, tag)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VGChangeDelTag indicates an expected call of VGChangeDelTag.
func (mr *MockCommandsMockRecorder) VGChangeDelTag(ctx, vGName, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VGChangeDelTag", reflect.TypeOf((*MockCommands)(nil).VGChangeDelTag), ctx, vGName, tag)
}

// VGLockStart mocks base method.
func (m *MockCommands) VGLockStart(ctx context.Context, vgName string, hostID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VGLockStart", ctx, vgName, hostID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VGLockStart indicates an expected call of VGLockStart.
func (mr *MockCommandsMockRecorder) VGLockStart(ctx, vgName, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VGLockStart", reflect.TypeOf((*MockCommands)(nil).VGLockStart), ctx, vgName, hostID)
}

// VGLockStop mocks base method.
func (m *MockCommands) VGLockStop(ctx context.Context, vgName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VGLockStop", ctx, vgName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VGLockStop indicates an expected call of VGLockStop.
func (mr *MockCommandsMockRecorder) VGLockStop(ctx, vgName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VGLockStop", reflect.TypeOf((*MockCommands)(nil).VGLockStop), ctx, vgName)
}

// VGScan mocks base method.
func (m *MockCommands) VGScan(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VGScan", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VGScan indicates an expected call of VGScan.
func (mr *MockCommandsMockRecorder) VGScan(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VGScan", reflect.TypeOf((*MockCommands)(nil).VGScan), ctx)
}

// WipeDMTable mocks base method.
func (m *MockCommands) WipeDMTable(ctx context.Context, dmName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WipeDMTable", ctx, dmName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WipeDMTable indicates an expected call of WipeDMTable.
func (mr *MockCommandsMockRecorder) WipeDMTable(ctx, dmName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WipeDMTable", reflect.TypeOf((*MockCommands)(nil).WipeDMTable), ctx, dmName)
}
