type: object
properties:
  disableDs:
    description: Выключить sds-node-configurator daemonset
  logLevel:
    description: Уровень логирования для приложений модуля
  enableThinProvisioning:
    description: Включить поддержку thin LVM томов
  storageNetworkCIDRs:
    description: CIDR-блоки для выделенной сети Storage. Используйте этот параметр только если к узлам Вашего кластера подключена выделенная сеть для системы хранения данных (СХД).
    example: ["10.1.1.0/24"]
    x-examples:
    - []
    - ["1.2.3.0/24", "3.2.1.0/16"]
