//go:build !ignore_autogenerated

/*
Copyright  Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDevice) DeepCopyInto(out *BlockDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDevice.
func (in *BlockDevice) DeepCopy() *BlockDevice {
	if in == nil {
		return nil
	}
	out := new(BlockDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlockDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDeviceFilter) DeepCopyInto(out *BlockDeviceFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDeviceFilter.
func (in *BlockDeviceFilter) DeepCopy() *BlockDeviceFilter {
	if in == nil {
		return nil
	}
	out := new(BlockDeviceFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlockDeviceFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDeviceFilterList) DeepCopyInto(out *BlockDeviceFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlockDeviceFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDeviceFilterList.
func (in *BlockDeviceFilterList) DeepCopy() *BlockDeviceFilterList {
	if in == nil {
		return nil
	}
	out := new(BlockDeviceFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlockDeviceFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDeviceFilterSpec) DeepCopyInto(out *BlockDeviceFilterSpec) {
	*out = *in
	if in.BlockDeviceSelector != nil {
		in, out := &in.BlockDeviceSelector, &out.BlockDeviceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDeviceFilterSpec.
func (in *BlockDeviceFilterSpec) DeepCopy() *BlockDeviceFilterSpec {
	if in == nil {
		return nil
	}
	out := new(BlockDeviceFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDeviceList) DeepCopyInto(out *BlockDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlockDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDeviceList.
func (in *BlockDeviceList) DeepCopy() *BlockDeviceList {
	if in == nil {
		return nil
	}
	out := new(BlockDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlockDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDeviceStatus) DeepCopyInto(out *BlockDeviceStatus) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDeviceStatus.
func (in *BlockDeviceStatus) DeepCopy() *BlockDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(BlockDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolume) DeepCopyInto(out *LVMLogicalVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(LVMLogicalVolumeStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolume.
func (in *LVMLogicalVolume) DeepCopy() *LVMLogicalVolume {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LVMLogicalVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolumeList) DeepCopyInto(out *LVMLogicalVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LVMLogicalVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolumeList.
func (in *LVMLogicalVolumeList) DeepCopy() *LVMLogicalVolumeList {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LVMLogicalVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolumeSnapshot) DeepCopyInto(out *LVMLogicalVolumeSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(LVMLogicalVolumeSnapshotStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolumeSnapshot.
func (in *LVMLogicalVolumeSnapshot) DeepCopy() *LVMLogicalVolumeSnapshot {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolumeSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LVMLogicalVolumeSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolumeSnapshotList) DeepCopyInto(out *LVMLogicalVolumeSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LVMLogicalVolumeSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolumeSnapshotList.
func (in *LVMLogicalVolumeSnapshotList) DeepCopy() *LVMLogicalVolumeSnapshotList {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolumeSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LVMLogicalVolumeSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolumeSnapshotSpec) DeepCopyInto(out *LVMLogicalVolumeSnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolumeSnapshotSpec.
func (in *LVMLogicalVolumeSnapshotSpec) DeepCopy() *LVMLogicalVolumeSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolumeSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolumeSnapshotStatus) DeepCopyInto(out *LVMLogicalVolumeSnapshotStatus) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	out.UsedSize = in.UsedSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolumeSnapshotStatus.
func (in *LVMLogicalVolumeSnapshotStatus) DeepCopy() *LVMLogicalVolumeSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolumeSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolumeSource) DeepCopyInto(out *LVMLogicalVolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolumeSource.
func (in *LVMLogicalVolumeSource) DeepCopy() *LVMLogicalVolumeSource {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolumeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolumeSpec) DeepCopyInto(out *LVMLogicalVolumeSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(LVMLogicalVolumeSource)
		**out = **in
	}
	if in.Thin != nil {
		in, out := &in.Thin, &out.Thin
		*out = new(LVMLogicalVolumeThinSpec)
		**out = **in
	}
	if in.Thick != nil {
		in, out := &in.Thick, &out.Thick
		*out = new(LVMLogicalVolumeThickSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeCleanup != nil {
		in, out := &in.VolumeCleanup, &out.VolumeCleanup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolumeSpec.
func (in *LVMLogicalVolumeSpec) DeepCopy() *LVMLogicalVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolumeStatus) DeepCopyInto(out *LVMLogicalVolumeStatus) {
	*out = *in
	out.ActualSize = in.ActualSize.DeepCopy()
	if in.Contiguous != nil {
		in, out := &in.Contiguous, &out.Contiguous
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolumeStatus.
func (in *LVMLogicalVolumeStatus) DeepCopy() *LVMLogicalVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolumeThickSpec) DeepCopyInto(out *LVMLogicalVolumeThickSpec) {
	*out = *in
	if in.Contiguous != nil {
		in, out := &in.Contiguous, &out.Contiguous
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolumeThickSpec.
func (in *LVMLogicalVolumeThickSpec) DeepCopy() *LVMLogicalVolumeThickSpec {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolumeThickSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMLogicalVolumeThinSpec) DeepCopyInto(out *LVMLogicalVolumeThinSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMLogicalVolumeThinSpec.
func (in *LVMLogicalVolumeThinSpec) DeepCopy() *LVMLogicalVolumeThinSpec {
	if in == nil {
		return nil
	}
	out := new(LVMLogicalVolumeThinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroup) DeepCopyInto(out *LVMVolumeGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroup.
func (in *LVMVolumeGroup) DeepCopy() *LVMVolumeGroup {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LVMVolumeGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupDevice) DeepCopyInto(out *LVMVolumeGroupDevice) {
	*out = *in
	out.DevSize = in.DevSize.DeepCopy()
	out.PVSize = in.PVSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupDevice.
func (in *LVMVolumeGroupDevice) DeepCopy() *LVMVolumeGroupDevice {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupList) DeepCopyInto(out *LVMVolumeGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LVMVolumeGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupList.
func (in *LVMVolumeGroupList) DeepCopy() *LVMVolumeGroupList {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LVMVolumeGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupLocalSpec) DeepCopyInto(out *LVMVolumeGroupLocalSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupLocalSpec.
func (in *LVMVolumeGroupLocalSpec) DeepCopy() *LVMVolumeGroupLocalSpec {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupLocalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupNode) DeepCopyInto(out *LVMVolumeGroupNode) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]LVMVolumeGroupDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupNode.
func (in *LVMVolumeGroupNode) DeepCopy() *LVMVolumeGroupNode {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupSet) DeepCopyInto(out *LVMVolumeGroupSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupSet.
func (in *LVMVolumeGroupSet) DeepCopy() *LVMVolumeGroupSet {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LVMVolumeGroupSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupSetList) DeepCopyInto(out *LVMVolumeGroupSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LVMVolumeGroupSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupSetList.
func (in *LVMVolumeGroupSetList) DeepCopy() *LVMVolumeGroupSetList {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LVMVolumeGroupSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupSetSpec) DeepCopyInto(out *LVMVolumeGroupSetSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.LVGTemplate.DeepCopyInto(&out.LVGTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupSetSpec.
func (in *LVMVolumeGroupSetSpec) DeepCopy() *LVMVolumeGroupSetSpec {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupSetStatus) DeepCopyInto(out *LVMVolumeGroupSetStatus) {
	*out = *in
	if in.CreatedLVGs != nil {
		in, out := &in.CreatedLVGs, &out.CreatedLVGs
		*out = make([]LVMVolumeGroupSetStatusLVG, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupSetStatus.
func (in *LVMVolumeGroupSetStatus) DeepCopy() *LVMVolumeGroupSetStatus {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupSetStatusLVG) DeepCopyInto(out *LVMVolumeGroupSetStatusLVG) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupSetStatusLVG.
func (in *LVMVolumeGroupSetStatusLVG) DeepCopy() *LVMVolumeGroupSetStatusLVG {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupSetStatusLVG)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupSpec) DeepCopyInto(out *LVMVolumeGroupSpec) {
	*out = *in
	if in.BlockDeviceSelector != nil {
		in, out := &in.BlockDeviceSelector, &out.BlockDeviceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ThinPools != nil {
		in, out := &in.ThinPools, &out.ThinPools
		*out = make([]LVMVolumeGroupThinPoolSpec, len(*in))
		copy(*out, *in)
	}
	out.Local = in.Local
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupSpec.
func (in *LVMVolumeGroupSpec) DeepCopy() *LVMVolumeGroupSpec {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupStatus) DeepCopyInto(out *LVMVolumeGroupStatus) {
	*out = *in
	out.AllocatedSize = in.AllocatedSize.DeepCopy()
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]LVMVolumeGroupNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ThinPools != nil {
		in, out := &in.ThinPools, &out.ThinPools
		*out = make([]LVMVolumeGroupThinPoolStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.VGSize = in.VGSize.DeepCopy()
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.VGFree = in.VGFree.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupStatus.
func (in *LVMVolumeGroupStatus) DeepCopy() *LVMVolumeGroupStatus {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupTemplate) DeepCopyInto(out *LVMVolumeGroupTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	if in.BlockDeviceSelector != nil {
		in, out := &in.BlockDeviceSelector, &out.BlockDeviceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ThinPools != nil {
		in, out := &in.ThinPools, &out.ThinPools
		*out = make([]LVMVolumeGroupThinPoolSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupTemplate.
func (in *LVMVolumeGroupTemplate) DeepCopy() *LVMVolumeGroupTemplate {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupTemplateMeta) DeepCopyInto(out *LVMVolumeGroupTemplateMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupTemplateMeta.
func (in *LVMVolumeGroupTemplateMeta) DeepCopy() *LVMVolumeGroupTemplateMeta {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupTemplateMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupThinPoolSpec) DeepCopyInto(out *LVMVolumeGroupThinPoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupThinPoolSpec.
func (in *LVMVolumeGroupThinPoolSpec) DeepCopy() *LVMVolumeGroupThinPoolSpec {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupThinPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LVMVolumeGroupThinPoolStatus) DeepCopyInto(out *LVMVolumeGroupThinPoolStatus) {
	*out = *in
	out.ActualSize = in.ActualSize.DeepCopy()
	out.UsedSize = in.UsedSize.DeepCopy()
	out.AllocatedSize = in.AllocatedSize.DeepCopy()
	out.AvailableSpace = in.AvailableSpace.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LVMVolumeGroupThinPoolStatus.
func (in *LVMVolumeGroupThinPoolStatus) DeepCopy() *LVMVolumeGroupThinPoolStatus {
	if in == nil {
		return nil
	}
	out := new(LVMVolumeGroupThinPoolStatus)
	in.DeepCopyInto(out)
	return out
}
