---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: blockdevices.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: BlockDevice
    plural: blockdevices
    singular: blockdevice
    shortNames:
      - bd
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            BlockDevice is a Kubernetes Custom Resource that contains actual and useful information about associated block devices  which might be used by a SDS-Node-Configurator controller to perform operations such as Volume Group creation, Physical Volume extensions and so on.
            
            > This kind of resources is necessary for successful and correct the controller's work-flow. The filling of resource's configuration process is fully automatic and it is done by the controller itself.
          properties:
            status:
              type: object
              description: |
                Defines current state of the device.
              required: [size,type,consumable,path,rota,hotPlug,nodeName,machineId]
              properties:
                type:
                  type: string
                  description: |
                    The device's type.
                fsType:
                  type: string
                  enum: [LVM2_member, ""]
                  description: |
                    The device's file system type. The controller supports empty (without any fs) or LVM2_member values.
                nodeName:
                  type: string
                  description: |
                    A node's name the device is on.
                consumable:
                  type: boolean
                  description: |
                    Special flag that defines if the device might be used by the controller.
                pvUUID:
                  type: string
                  description: |
                    The Physical Volume's UUID.
                    
                    > Optional: exists if only the device is used as a Physical Volume.
                vgUUID:
                  type: string
                  description: | 
                    The Volume Group's UUID.

                    > Optional: exists if only the device is used as a Physical Volume and included in a Volume Group.
                lvmVolumeGroupName:
                  type: string
                  description: | 
                    The LVMVolumeGroup resource's name. 
                    
                    > Optional: exists if only the device is used as a Physical Volume, and included in a Volume Group and LVMVolumeGroup resource.
                actualVGNameOnTheNode:
                  type: string
                  description: |
                    The Volume Group's name the device is included in.
                    
                    > Optional: exists if only the device is used as a Physical Volume and included in a Volume Group.
                wwn:
                  type: string
                  description: |
                    The device's unique wwn (World Wide Name) identifier.
                    
                    > Optional: might be empty if no WWN was set.
                serial:
                  type: string
                  description: |
                    The device's serial unique number.
                path:
                  type: string
                  description: |
                    The device's path (name).
                size:
                  type: string
                  description: |
                    The device's size.
                model:
                  type: string
                  description: |
                    The device's model.
                    
                    > Optional: might be empty if no model was set.
                rota:
                  type: boolean
                  description: |
                    The device's media type. Might be 'True' for HHD and 'False' for SSD.
                hotPlug:
                  type: boolean
                  description: |
                    The device's connection type. Might be 'True' if the device had been hotPlugged, otherwise - 'False'.
                machineId:
                  type: string
                  description: |
                    The machine's unique identifier the device is on.
      additionalPrinterColumns:
        - jsonPath: .status.nodeName
          name: Node
          type: string
          description: The node th–µ block device is on.
        - jsonPath: .status.consumable
          name: Consumable
          type: boolean
          description: If current block device might be used by sds-node-configurator.
        - jsonPath: .status.size
          name: Size
          type: string
          description: Size of included device.
        - jsonPath: .status.path
          name: Path
          type: string
          description: Actual device path (name).
          priority: 1
        - jsonPath: .status.actualVGNameOnTheNode
          name: VG
          type: string
          description: The Volume Group the block device is in.
          priority: 1
        - jsonPath: .status.lvmVolumeGroupName
          name: LVMVolumeGroup
          type: string
          description: The LVMVolumeGroup resource the block device is in.
          priority: 1
