---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: blockdevices.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: BlockDevice
    plural: blockdevices
    singular: blockdevice
    shortNames:
      - bd
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            BlockDevice is a Kubernetes Custom Resource that displays actual information about block devices, which might be used by the sds-node-configurator controller to create Volume Groups, extend Physical Volumes, and so on.
            
            > The resource is created and managed by the controller only.
          properties:
            status:
              type: object
              description: |
                Defines the current device state.
              required: [size,type,consumable,path,rota,hotPlug,nodeName,machineId]
              properties:
                type:
                  type: string
                  description: |
                    The device's type.
                fsType:
                  type: string
                  enum: [LVM2_member, ""]
                  description: |
                    The device's file system type.
                nodeName:
                  type: string
                  description: |
                    The name of the kubernetes node the device is on.
                consumable:
                  type: boolean
                  description: |
                    The flag that defines whether this device can be used by the controller.
                pvUUID:
                  type: string
                  description: |
                    The Physical Volume UUID.
                    
                    > Optional: exists only if the device is used as a Physical Volume.
                vgUUID:
                  type: string
                  description: | 
                    The Volume Group UUID.

                    > Optional: exists only if the device is used as a Physical Volume and is included in a Volume Group.
                lvmVolumeGroupName:
                  type: string
                  description: | 
                    The LVMVolumeGroup resource name. 
                    
                    > Optional: exists only if the device is used as a Physical Volume and is included in a Volume Group and LVMVolumeGroup resource.
                actualVGNameOnTheNode:
                  type: string
                  description: |
                    The actual name of the Volume Group the device is included in.
                    
                    > Optional: exists if only the device is used as a Physical Volume and is included in a Volume Group.
                wwn:
                  type: string
                  description: |
                    The device unique wwn (World Wide Name) identifier.
                    
                    > Optional: might be empty if no WWN was set.
                serial:
                  type: string
                  description: |
                    The device unique serial number.
                path:
                  type: string
                  description: |
                    The device path (name).
                size:
                  type: string
                  description: |
                    The device size.
                model:
                  type: string
                  description: |
                    The device model.
                    
                    > Optional: might be empty if no model was set.
                rota:
                  type: boolean
                  description: |
                    The device media type. Might be:
                    - 'True' (for HHD)
                    - 'False' (for SSD)
                hotPlug:
                  type: boolean
                  description: |
                    The device connection type. Might be:
                    - 'True' (if the device has been hotPlugged)
                    - 'False' (otherwise)
                machineId:
                  type: string
                  description: |
                    The unique identifier of the machine the device is on (normally at /etc/machine-id)
      additionalPrinterColumns:
        - jsonPath: .status.nodeName
          name: Node
          type: string
          description: The node the block device is on.
        - jsonPath: .status.consumable
          name: Consumable
          type: boolean
          description: Defines whether the current block device can be used by sds-node-configurator.
        - jsonPath: .status.size
          name: Size
          type: string
          description: Size of the included device.
        - jsonPath: .status.path
          name: Path
          type: string
          description: Actual device path (name).
          priority: 1
        - jsonPath: .status.actualVGNameOnTheNode
          name: VG
          type: string
          description: The Volume Group the block device is in.
          priority: 1
        - jsonPath: .status.lvmVolumeGroupName
          name: LVMVolumeGroup
          type: string
          description: The LVMVolumeGroup resource the block device is in.
          priority: 1
