---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: blockdevices.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    plural: сonsumableblockdevices
    singular: сonsumableblockdevice
    kind: ConsumableBlockDevice
    shortNames:
      - bd
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "empty block devices"
          properties:
            status:
              type: object
              properties:
                nodename:
                  type: string
                  description: "node name"
                id:
                  type: string
                  description: "id"
                path:
                  type: string
                  description: "path"
                size:
                  type: string
                  description: "size"
                model:
                  type: string
                  description: "model"
