---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lvgmigrations.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: LVGMigration
    plural: lvgmigrations
    singular: lvgmigration
    shortNames:
      - lvgmigration
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            The existence of the object marks that the LvmVolumeGroup to LVMVolumeGroup resources migration has been completed.
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                completed:
                  type: boolean
                  description: |
                    Shows LvmVolumeGroup migration status.
                  default: True
