---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lvmlogicalvolumes.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: LVMLogicalVolume
    plural: lvmlogicalvolumes
    singular: lvmlogicalvolume
    shortNames:
      - llv
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: | 
            The LVMLogicalVolume resource defines the storage where a PV will be created in.
          required:
            - spec
          properties:
            spec:
              type: object
              x-kubernetes-validations:
                - rule: |
                    (self.type == "Thin" && has(self.thin)) || self.type != "Thin"
                  message: "Field 'thin' is required when 'type' is 'Thin'."
              required:
                - actualLVNameOnTheNode
                - type
                - lvmVolumeGroupName
                - size
              properties:
                actualLVNameOnTheNode:
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                type:
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  enum: [Thick, Thin]
                size:
                  type: string
                  minLength: 1
                  pattern: '^[0-9]+(\.[0-9]+)?(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$'
                lvmVolumeGroupName:
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  minLength: 1
                  pattern: '^[a-z0-9]([a-z0-9-.]{0,251}[a-z0-9])?$'
                thin:
                  type: object
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  required:
                    - poolName
                  properties:
                    poolName:
                      type: string
                      minLength: 1
                      pattern: ^.*$
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: [Created, Pending, Resizing, Failed]
                reason:
                  type: string
                actualSize:
                  type: string
      additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Phase
          type: string
          description: The current resource status.
        - jsonPath: .spec.lvmVolumeGroupName
          name: LVMVolumeGroup
          type: string
          description: The selected LVMVolumeGroup resource.
        - jsonPath: .spec.thin.poolName
          name: ThinPool
          type: string
          description: The selected ThinPool in LVMVolumeGroup. Might be empty if the LVMVolumeGroup is thick.
        - jsonPath: .status.actualSize
          name: Size
          type: string
          description: Actual LVMLogicalVolume size.
