---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lvmlogicalvolumes.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: LVMLogicalVolume
    plural: lvmlogicalvolumes
    singular: lvmlogicalvolume
    shortNames:
      - llv
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: | 
            The LVMLogicalVolume resource defines the storage where a PV will be created in.
          properties:
            spec:
              type: object
              properties:
                type:
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                  type: string
                  enum: [Thick, Thin]
                size:
                  type: string
                lvmVolumeGroup:
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                  type: string
                thin:
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                  type: object
                  properties:
                    poolName:
                      type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: [Created, Pending, Resizing, Failed]
                reason:
                  type: string
                actualSize:
                  type: string
      additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Phase
          type: string
          description: The current resource status.
        - jsonPath: .spec.lvmVolumeGroup
          name: LVMVolumeGroup
          type: string
          description: The selected LVMVolumeGroup resource.
        - jsonPath: .spec.thin.poolName
          name: ThinPool
          type: string
          description: The selected ThinPool in LVMVolumeGroup. Might be empty if the LVMVolumeGroup is thick.
        - jsonPath: .status.actualSize
          name: Size
          type: string
          description: Actual LVMLogicalVolume size.
