---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lvmvolumegroups.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
  finalizers:
    - storage.deckhouse.io/sds-node-configurator
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: LvmVolumeGroup
    plural: lvmvolumegroups
    singular: lvmvolumegroup
    shortNames:
      - lvg
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "LVM volume group"
          properties:
            spec:
              type: object
              required: [type,blockDeviceNames,actualVGnameOnTheNode]
              properties:
                type:
                  type: string
                  enum: [local,shared]
                  description: "LVMVolumeGroup type. Immutable field"
                blockDeviceNames:
                  type: array
                  items:
                    type: string
                  description: "Array of block devices names"
                actualVGNameOnTheNode:
                  type: string
                  description: "VG name on the node. Immutable field"
                thinPools:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: "Thin pool's name"
                      size:
                        type: string
                        description: "Thin pool's size"
            status:
              type: object
              required: [health,allocationType,vgUUID,vgSize,allocatedSize,nodes]
              properties:
                health:
                  type: string
                  enum: [operational,nonoperational]
                  description: "Describes if VG is actually healthy"
                message:
                  type: string
                  description: "Description of the problem"
                allocationType:
                  type: string
                  enum: [thin,thick]
                vgUUID:
                  type: string
                vgSize:
                  type: string
                allocatedSize:
                  type: string
                thinPoolSize:
                  type: string
                nodes:
                  type: array
                  items:
                    type: object
                    required: [name,devices]
                    properties:
                      name:
                        type: string
                      devices:
                        type: array
                        items:
                          type: object
                          required: [path,pvSize,devSize,pvUUID,blockDevice]
                          properties:
                            path:
                              type: string
                            pvSize:
                              type: string
                            devSize:
                              type: string
                            pvUUID:
                              type: string
                            blockDevice:
                              type: string