---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lvmvolumegroupsets.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: sds-node-configurator
    backup.deckhouse.io/cluster-config: "true"
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: LVMVolumeGroupSet
    plural: lvmvolumegroupsets
    singular: lvmvolumegroupset
    shortNames:
      - lvgset
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            An interface for creating several LVMVolumeGroups by common template at once.
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - strategy
                - lvmVolumeGroupTemplate
                - nodeSelector
              properties:
                strategy:
                  type: string
                  description: |
                    Strategy (rule) to provide LVMVolumeGroup resources by the set.
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: "The strategy field is immutable."
                  enum:
                    - PerNode
                nodeSelector:
                  type: object
                  description: |
                    Node selector for nodes that will be used by LVMVolumeGroups.
                  properties:
                    matchLabels:
                      type: object
                      description: |
                        Labels for the node selector.
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      description: |
                        Expressions for the node selector.
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                            description: |
                              Label key to check.
                          operator:
                            type: string
                            description: |
                              Operator for comparing values.
                            enum:
                              - In
                              - NotIn
                              - Exists
                              - DoesNotExist
                          values:
                            type: array
                            description: |
                              An array of values to compare. Required if the operator is `In` or `NotIn`.
                            items:
                              type: string
                lvmVolumeGroupTemplate:
                  type: object
                  description: |
                    Common template for LVMVolumeGroup resources provided by the set.
                  required:
                    - type
                    - actualVGNameOnTheNode
                    - blockDeviceSelector
                  properties:
                    blockDeviceSelector:
                      type: object
                      description: |
                        BlockDevice resources selector used in LVMVolumeGroups configurations.
                      properties:
                        matchLabels:
                          type: object
                          description: |
                            Labels for the block device selector.
                          additionalProperties:
                            type: string
                        matchExpressions:
                          type: array
                          description: |
                            Expressions for the block device selector.
                          items:
                            type: object
                            properties:
                              key:
                                type: string
                                description: |
                                  Label key to check.
                              operator:
                                type: string
                                description: |
                                  Operator for comparing values.
                                enum:
                                  - In
                                  - NotIn
                                  - Exists
                                  - DoesNotExist
                              values:
                                type: array
                                description: |
                                  An array of values to compare. Required if the operator is `In` or `NotIn`.
                                items:
                                  type: string
                    metadata:
                      type: object
                      description: |
                        Metadata of LVMVolumeGroup resources.
                      properties:
                        labels:
                          type: object
                          additionalProperties:
                            type: string
                          description: |
                            Required labels for LVMVolumeGroup resources.
                    type:
                      type: string
                      description: |
                        Type of a VolumeGroup in LVMVolumeGroups.
                        
                        Possible values:
                        
                        - `Local`: Local volume group; the devices used are not distributed (not Shared LUN).
                      enum:
                        - Local
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: "The type field is immutable."
                    actualVGNameOnTheNode:
                      type: string
                      description: |
                        Desired name of a Volume Group in LVMVolumeGroups. Must be unique for the node it is on.
                        
                        > This field is immutable.
                        > Note that this Volume Group name will be common for every LVMVolumeGroup created by the set.
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: "The actualVGNameOnTheNode field is immutable."
                    thinPools:
                      type: array
                      description: |
                        Desired thin pool configuration in LVMVolumeGroups.
                        
                        > Note that the configuration will be common for every LVMVolumeGroup created by the set.
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: |
                              Desired thin pool name.
                              
                              > This field is immutable.
                          size:
                            x-kubernetes-int-or-string: true
                            pattern: '^[0-9]+(\.[0-9]+)?(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$|^[1-9][0-9]?%$|100%'
                            description: |
                              Desired thin pool size. Might be specified as a number or percentage of total Volume Group space.
                              
                              > Note that if you specify the percent size, the thin pool will be automatically extended when Volume Group is extended.
                          allocationLimit:
                            type: string
                            pattern: '^[1-9][0-9]{2,3}%$'
                            default: "150%"
                            description: |
                              Thin pool oversize limit.
                        required:
                          - name
                          - size
            status:
              type: object
              properties:
                createdLVMVolumeGroups:
                  type: array
                  description: |
                    Brief information about LVMVolumeGroups created by the set.
                  items:
                    type: object
                    properties:
                      lvmVolumeGroupName:
                        type: string
                        description: |
                          Name of the created LVMVolumeGroup resource.
                      nodeName:
                        type: string
                        description: |
                          Name of the node where the LVMVolumeGroup resource was created.
                currentLVMVolumeGroupsCount:
                  type: integer
                  description: |
                    Current number of LVMVolumeGroups created by the set.
                desiredLVMVolumeGroupsCount:
                  type: integer
                  description: |
                    Desired number of LVMVolumeGroups that should be created by the set.
                phase:
                  type: string
                  description: |
                    LVMVolumeGroups creation phase.
                  enum:
                    - Created
                    - Pending
                    - NotCreated
                    - ""
                reason:
                  type: string
                  description: |
                    Reason for the current phase.
      subresources:
        status: { }
      additionalPrinterColumns:
        - jsonPath: .spec.strategy
          name: Strategy
          type: string
          description: Specified LVMVolumeGroups strategy creation.
        - jsonPath: .spec.lvmVolumeGroupTemplate.actualVGNameOnTheNode
          name: VG
          type: string
          description: Actual Volume Group name.
        - jsonPath: .spec.lvmVolumeGroupTemplate.type
          name: type
          type: string
          description: Volume Group type.
          priority: 1
        - jsonPath: .status.currentLVMVolumeGroupsCount
          name: Current LVG Count
          type: integer
          description: Current LVMVolumeGroups count created by the set.
        - jsonPath: .status.desiredLVMVolumeGroupsCount
          name: Desired LVG Count
          type: integer
          description: Desired LVMVolumeGroups count created by the set.
        - jsonPath: .status.phase
          name: Phase
          type: string
          description: Resource phase.
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          description: Age of this resource.
