---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lvmvolumegroups.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: LvmVolumeGroup
    plural: lvmvolumegroups
    singular: lvmvolumegroup
    shortNames:
      - lvg
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            An interface for managing Volume Groups and Thin pools on the nodes.
            
            > These resources might be created both by a user and the sds-node-configurator controller. The sds-node-configurator controller will automatically create an LVMVolumeGroup resource if it detects an existing Volume Group on a node tagged with 'storage.deckhouse.io/enabled=true'. The controller will fill in both the 'spec' and 'status' fields.
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - type
                - blockDeviceNames
                - actualVGNameOnTheNode
              properties:
                type:
                  type: string
                  description: |
                    The type of a Volume Group. Might be:
                    - Local, that is, local if the devices used are not distributed (not Shared LUN).
                  enum:
                    - Local
                blockDeviceNames:
                  type: array
                  description: |
                    An array of block device resource names to create a Volume Group.
                    
                    > Note that the selected block devices must belong to the same node for a Local Volume Group.
                  items:
                    type: string
                actualVGNameOnTheNode:
                  type: string
                  description: |
                    The desired name of a Volume Group. Must be unique for the node it is on.
                    
                    > This field is immutable.
                thinPools:
                  type: array
                  description: |
                    The desired Thin-pool configuration.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: |
                          The desired Thin-pool name.
                          
                          > This field is immutable.
                      size:
                        type: string
                        pattern: '^[0-9]+(\.[0-9]+)?(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$'
                        description: |
                          The desired Thin-pool size.
                      allocationLimit:
                        type: string
                        pattern: '^[1-9][0-9]{2,}%$'
                        default: "150%"
                        description: |
                          Thin pool oversize limit. Default is 150%.
                    required:
                      - name
                      - size
            status:
              type: object
              properties:
                thinPoolReady:
                  type: string
                  description: |
                    Shows the healthy and total Thin-pool count.
                configurationApplied:
                  type: string
                  description: |
                    Show if last configuration has been successfully applied.
                phase:
                  type: string
                  description: |
                    The general LVMVolumeGroup condition.
                  enum:
                    - Pending
                    - Ready
                    - NotReady
                    - Terminating
                    - ""
                conditions:
                  description: |
                    The LVMVolumeGroup conditions.
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: |
                          The condition type.
                        enum:
                          - VGConfigurationApplied
                          - VGReady
                          - NodeReady
                          - AgentReady
                          - Ready
                      status:
                        type: string
                        description: |
                          The condition status.
                      reason:
                        type: string
                        description: |
                          The reason of the current status.
                      message:
                        type: string
                        description: |
                          The information about the current status.
                      lastTransitionTime:
                        type: string
                        description: |
                          The time the condition was updated.
                      observedGeneration:
                        type: integer
                        description: |
                          The resource version when the condition applied.
                vgUUID:
                  type: string
                  description: |
                    The Volume Group UUID.
                vgSize:
                  type: string
                  description: |
                    The Volume Group capacity.
                allocatedSize:
                  type: string
                  description: |
                    The amount of space currently occupied on the Volume Group.
                thinPools:
                  type: array
                  description: |
                    The current state of the Volume Group's Thin-pool.
                    
                    > Might be empty if there is no any Thin-pool in the Volume Group.
                  items:
                    type: object
                    required:
                      - name
                      - actualSize
                      - usedSize
                    properties:
                      name:
                        type: string
                        description: |
                          The Thin-pool name.
                      actualSize:
                        type: string
                        description: |
                          The Thin-pool capacity.
                      usedSize:
                        type: string
                        description: |
                          The Thin-pool used size.
                      allocatedSize:
                        type: string
                        description: |
                          Total LVs request size in the thin-pool.
                      allocationLimit:
                        type: string
                        description: |
                          Thin pool oversize limit. Default is 150%.
                        default: "150%"
                        pattern: '^[1-9][0-9]{2,}%$'
                      ready:
                        type: boolean
                        description: |
                          The Thin-pool health status.
                      message:
                        type: string
                        description: |
                          Information about the status.
                nodes:
                  type: array
                  description: |
                   Information about the nodes the Volume Group is on.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: |
                          The node name.
                      devices:
                        type: array
                        description: |
                          Information about the devices used in the Volume Group on the current node.
                        items:
                          type: object
                          properties:
                            path:
                              type: string
                              description: |
                                The device path on the node (e.g., /dev/sda).
                            pvSize:
                              type: string
                              description: |
                                The Physical Volume size.
                            devSize:
                              type: string
                              description: |
                                The block device size.
                            pvUUID:
                              type: string
                              description: |
                                The LVM Physical Volume UUID.
                            blockDevice:
                              type: string
                              description: |
                                The name of the corresponding block device resource.
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.thinPoolReady
          name: ThinPools
          type: string
          description: Current and total Thin pools count.
        - jsonPath: .status.configurationApplied
          name: Configuration Applied
          type: string
          description: If last configuration has been successfully applied.
        - jsonPath: .status.phase
          name: phase
          type: string
          description: Resource phase.
        - jsonPath: .status.nodes..name
          name: node
          type: string
          description: The node the VG is on.
        - jsonPath: .status.vgSize
          name: size
          type: string
          description: Total VG size.
        - jsonPath: .status.allocatedSize
          name: allocated size
          type: string
          description: Actual VG size.
        - jsonPath: .spec.actualVGNameOnTheNode
          name: VG
          type: string
          description: Actual VG name.
        - jsonPath: .spec.type
          name: type
          type: string
          description: Volume Group type.
          priority: 1
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          description: The age of this resource
