---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lvmvolumegroups.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: LvmVolumeGroup
    plural: lvmvolumegroups
    singular: lvmvolumegroup
    shortNames:
      - lvg
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "LVM volume group"
          properties:
            required:
              - spec
            spec:
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - Local
                    - Shared
                  description: "LVMVolumeGroup type. Immutable field"
                blockDeviceNames:
                  type: array
                  items:
                    type: string
                  description: "Array of block devices names"
                actualVGNameOnTheNode:
                  type: string
                  description: "VG name on the node. Immutable field"
                thinPools:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: "Thin pool's name"
                      size:
                        type: string
                        pattern: '^[0-9]+(\.[0-9]+)?(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$'
                        description: "Thin pool's size"
                    required:
                      - name
                      - size
            status:
              type: object
              properties:
                health:
                  type: string
                  enum:
                    - Operational
                    - Nonoperational
                  description: "Describes if VG is healthy"
                message:
                  type: string
                  description: "Description of the problem"
                vgUUID:
                  type: string
                vgSize:
                  type: string
                allocatedSize:
                  type: string
                thinPools:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - actualSize
                      - usedSize
                    properties:
                      name:
                        type: string
                      actualSize:
                        type: string
                      usedSize:
                        type: string
                nodes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      devices:
                        type: array
                        items:
                          type: object
                          properties:
                            path:
                              type: string
                            pvSize:
                              type: string
                            devSize:
                              type: string
                            pvUUID:
                              type: string
                            blockDevice:
                              type: string
