---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lvmvolumegroups.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: LvmVolumeGroup
    plural: lvmvolumegroups
    singular: lvmvolumegroup
    shortNames:
      - lvg
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            LVMVolumeGroup is a Kubernetes Custom Resource that defines a desired and a current state of a Volume Group.
            The resource allows users to manipulate with different Volume Groups and watch them from a single place using
            declarative programming.
            
            > This kind or resources might be created both by a user and the SDS-Node-Configurator controller. 
            To create a resource by themselves, user should fill the resource's 'Spec' field with a desired Volume Group's configuration, 
            so the controller will create the required Volume Group and fill the resource's 'Status' field with Volume Group's 
            current state information. 
            The SDS-Node-Configurator controller automatically creates a LVMVolumeGroup resource, if it finds an existing Volume Group
            on the node with the special tag 'storage.deckhouse.io/enabled=true', so the controller will fill both the 'Spec'
            and the 'Status' fields.
          required:
            - spec
          properties:
            spec:
              type: object
              description: |
                Defines a desired state of a Volume Group. Use these parameters to create or update a Volume Group. 
                
                > These params are not updated by the controller.
              properties:
                type:
                  type: string
                  description: |
                    A Volume Group's type. Might be:
                    - Local (if Volume Group's devices are on the same node)
                    - Shared (if Volume Group's devices are on the different nodes)
                    
                    > Note that the controller does not support 'Shared' type for now.
                  enum:
                    - Local
                    - Shared
                blockDeviceNames:
                  type: array
                  description: |
                    An array of block device resources names. Selected block devices will be used by the controller to create
                    a Volume Group.
                    
                    > Note that you have selected block devices on the same node for a Local Volume Group and a single block device
                    for a Shared one.
                  items:
                    type: string
                actualVGNameOnTheNode:
                  type: string
                  description: |
                    The desired name of a Volume Group. Must be unique for the node it is on.
                    
                    > Immutable field.
                thinPools:
                  type: array
                  description: |
                    A desired Thin-pools configuration of a Volume Group.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: |
                          A desired Thin-pool's name.
                          
                          > Immutable field.
                      size:
                        type: string
                        pattern: '^[0-9]+(\.[0-9]+)?(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$'
                        description: |
                          A desired Thin-pool's size.
                    required:
                      - name
                      - size
            status:
              type: object
              description: |
                Defines a current state of a Volume Group. These parameters should not be changed by a user.
                
                > These params are updated by the controller.
              properties:
                health:
                  type: string
                  description: |
                    A Volume Group's global state. Might be:
                    - Operational (if everything is fine)
                    - Nooperational (if there are some problems in the volume group)
                  enum:
                    - Operational
                    - Nonoperational
                message:
                  type: string
                  description: |
                    Additional information about a Volume Group's current state.
                vgUUID:
                  type: string
                  description: |
                    A Volume Group's unique number.
                vgSize:
                  type: string
                  description: |
                    A total Volume Group's size.
                allocatedSize:
                  type: string
                  description: |
                    An actual Volume Group's size.
                thinPools:
                  type: array
                  description: |
                    A Volume Group's Thin-pool's current state.
                    
                    > Might be empty if there is no any Thin-pool in the Volume Group.
                  items:
                    type: object
                    required:
                      - name
                      - actualSize
                      - usedSize
                    properties:
                      name:
                        type: string
                        description: |
                          A Thin-pool's name.
                      actualSize:
                        type: string
                        description: |
                          A Thin-pool's current total size.
                      usedSize:
                        type: string
                        description: |
                          A Thin-pool's used size.
                nodes:
                  type: array
                  description: |
                   Information about nodes a Volume Group is on.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: |
                          A node's name.
                      devices:
                        type: array
                        description: |
                          Information about the devices used in the Volume Group on the current node.
                        items:
                          type: object
                          properties:
                            path:
                              type: string
                              description: |
                                A device's path (name).
                            pvSize:
                              type: string
                              description: |
                                A device's Physical Volume's size.
                            devSize:
                              type: string
                              description: |
                                A device's actual size.
                            pvUUID:
                              type: string
                              description: |
                                A Physical Volume's unique number.
                            blockDevice:
                              type: string
                              description: |
                                An associated block device resource's name.
      additionalPrinterColumns:
        - jsonPath: .status.health
          name: health
          type: string
          description: Volume Group health.
        - jsonPath: .status.nodes..name
          name: node
          type: string
          description: The node the VG is on.
        - jsonPath: .status.vgSize
          name: size
          type: string
          description: Total VG size.
        - jsonPath: .status.allocatedSize
          name: allocated size
          type: string
          description: Actual VG size.
        - jsonPath: .spec.actualVGNameOnTheNode
          name: VG
          type: string
          description: Actual VG name.
          priority: 1
        - jsonPath: .spec.type
          name: type
          type: string
          description: Volume Group type.
          priority: 1