---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lvmvolumegroups.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: sds-node-configurator
    backup.deckhouse.io/cluster-config: "true"
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    kind: LVMVolumeGroup
    plural: lvmvolumegroups
    singular: lvmvolumegroup
    shortNames:
      - lvg
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            An interface for managing Volume Groups and Thin pools on the nodes.
            
            > These resources might be created both by a user and the `sds-node-configurator` controller. `sds-node-configurator` controller will automatically create an LVMVolumeGroup resource if it detects an existing Volume Group on a node tagged with 'storage.deckhouse.io/enabled=true'. Controller will fill in both the 'spec' and 'status' fields.
            > `spec.thinPools` field must be filled in by yourself.
          required:
            - spec
          properties:
            spec:
              type: object
              x-kubernetes-validations:
                - rule: |
                    (self.type == "Local" && has(self.local)) || self.type != "Local"
                  message: "The 'local' field is required when the 'type' field is 'Local'."
              required:
                - type
                - blockDeviceSelector
                - actualVGNameOnTheNode
              properties:
                type:
                  type: string
                  description: |
                    Type of a Volume Group.
                    
                    Possible values:
                    
                    - `Local`: Local volume group; the devices used are not distributed (not Shared LUN).
                  enum:
                    - Local
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: "The type field is immutable."
                local:
                  type: object
                  description: |
                    Desired configuration for a local Volume Group.
                  required:
                    - nodeName
                  properties:
                    nodeName:
                      type: string
                      description: |
                        Desired node for the LVM Volume Group.
                        
                        > This field is immutable.
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: "The nodeName field is immutable."
                blockDeviceSelector:
                  type: object
                  description: |
                    Desired block device selector.
                    
                    > Note: Selected block devices must belong to the same node for a volume group of type ‘Local’.
                  properties:
                    matchLabels:
                      type: object
                      description: |
                        Desired block device selector labels.
                      additionalProperties:
                        type: string
                    matchExpressions:
                      type: array
                      description: |
                        Desired block device selector expressions.
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                            description: |
                              Label key to check.
                          operator:
                            type: string
                            description: |
                              Operator used to compare values.
                            enum:
                              - In
                              - NotIn
                              - Exists
                              - DoesNotExist
                          values:
                            type: array
                            description: |
                              Array of values to compare. Required if the operator is `In` or `NotIn`.
                            items:
                              type: string
                actualVGNameOnTheNode:
                  type: string
                  description: |
                    Desired name of a Volume Group. Must be unique for the node it is on.
                    
                    > This field is immutable.
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: "The actualVGNameOnTheNode field is immutable."
                thinPools:
                  type: array
                  description: |
                    Desired thin pool configuration.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: |
                          Desired thin pool name.
                          
                          > This field is immutable.
                      size:
                        x-kubernetes-int-or-string: true
                        pattern: '^[0-9]+(\.[0-9]+)?(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$|^[1-9][0-9]?%$|100%'
                        description: |
                          Desired thin pool size. Might be specified as number or percent size of total Volume Group space.
                          
                          > Note, that if you specify the percent size, the thin pool will be automatically extended when Volume Group is extended.
                      allocationLimit:
                        type: string
                        pattern: '^[1-9][0-9]{2,3}%$'
                        default: "150%"
                        description: |
                          Thin pool oversize limit.
                    required:
                      - name
                      - size
            status:
              type: object
              properties:
                thinPoolReady:
                  type: string
                  description: |
                    Shows the number of healthy and total thin pools.
                configurationApplied:
                  type: string
                  description: |
                    Indicates if the last configuration has been successfully applied.
                phase:
                  type: string
                  description: |
                    General LVMVolumeGroup condition.
                  enum:
                    - Pending
                    - Ready
                    - NotReady
                    - Terminating
                    - ""
                conditions:
                  description: |
                    LVMVolumeGroup conditions.
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: |
                          Condition type.
                        enum:
                          - VGConfigurationApplied
                          - VGReady
                          - NodeReady
                          - AgentReady
                          - Ready
                      status:
                        type: string
                        description: |
                          Condition status.
                      reason:
                        type: string
                        description: |
                          Reason for the current status.
                      message:
                        type: string
                        description: |
                          Information about the current status.
                      lastTransitionTime:
                        type: string
                        description: |
                          Time the condition was updated.
                      observedGeneration:
                        type: integer
                        description: |
                          Resource version when the condition was applied.
                vgUUID:
                  type: string
                  description: |
                    Volume Group UUID.
                vgSize:
                  type: string
                  description: |
                    Volume Group capacity.
                vgFree:
                  type: string
                  description: |
                    Volume Group free space.
                allocatedSize:
                  type: string
                  description: |
                    Amount of space currently occupied on the Volume Group.
                thinPools:
                  type: array
                  description: |
                    Current state of the Volume Group's thin pools.
                    
                    > Might be empty if there are no thin pools in the Volume Group.
                  items:
                    type: object
                    required:
                      - name
                      - actualSize
                      - usedSize
                    properties:
                      name:
                        type: string
                        description: |
                          Thin pool name.
                      actualSize:
                        type: string
                        description: |
                          Thin pool capacity.
                      usedSize:
                        type: string
                        description: |
                          Thin pool used size.
                      allocatedSize:
                        type: string
                        description: |
                          Total requested size of logical volumes in the thin pool.
                      allocationLimit:
                        type: string
                        description: |
                          Thin pool oversize limit.
                        default: "150%"
                        pattern: '^[1-9][0-9]{2,3}%$'
                      availableSpace:
                        type: string
                        description: |
                          Thin pool free space available.
                      ready:
                        type: boolean
                        description: |
                          Thin pool health status.
                      message:
                        type: string
                        description: |
                          Information about the status.
                nodes:
                  type: array
                  description: |
                    Information about the nodes the Volume Group is on.
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: |
                          Node name.
                      devices:
                        type: array
                        description: |
                          Information about the devices used in the Volume Group on the current node.
                        items:
                          type: object
                          properties:
                            path:
                              type: string
                              description: |
                                Device path on the node (e.g., `/dev/sda`).
                            pvSize:
                              type: string
                              description: |
                                Physical Volume size.
                            devSize:
                              type: string
                              description: |
                                Block device size.
                            pvUUID:
                              type: string
                              description: |
                                LVM Physical Volume UUID.
                            blockDevice:
                              type: string
                              description: |
                                Name of the corresponding block device resource.
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.thinPoolReady
          name: ThinPools
          type: string
          description: Current and total Thin pools count.
        - jsonPath: .status.configurationApplied
          name: Configuration Applied
          type: string
          description: If last configuration has been successfully applied.
        - jsonPath: .status.phase
          name: phase
          type: string
          description: Resource phase.
        - jsonPath: .status.nodes..name
          name: node
          type: string
          description: Node the Volume Group is on.
        - jsonPath: .status.vgSize
          name: size
          type: string
          description: Total Volume Group size.
        - jsonPath: .status.allocatedSize
          name: allocated size
          type: string
          description: Actual Volume Group size.
        - jsonPath: .spec.actualVGNameOnTheNode
          name: VG
          type: string
          description: Actual Volume Group name.
        - jsonPath: .spec.type
          name: type
          type: string
          description: Volume Group type.
          priority: 1
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          description: Age of this resource.
