---
apiVersion: v1
kind: Secret
metadata:
  name: registry
  namespace: d8-system
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.deckhouseAdmin.registry.dockercfg }}
