{{- if (.Values.global.enabledModules | has "operator-prometheus-crd") }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sds-health-watcher-controller
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list $ (dict "prometheus" "main")) | nindent 2 }}
spec:
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    bearerTokenSecret:
      name: "prometheus-token"
      key: "token"
    tlsConfig:
      insecureSkipVerify: true
    relabelings:
    - regex: endpoint|namespace|pod|container
      action: labeldrop
    - targetLabel: job
      replacement: sds-health-watcher-controller
    - targetLabel: tier
      replacement: cluster
    - sourceLabels: [__meta_kubernetes_endpointslice_endpoint_conditions_ready]
      regex: "true"
      action: keep
  selector:
    matchLabels:
      app.kubernetes.io/instance: sds-health-watcher-controller
      app.kubernetes.io/managed-by: Helm
  namespaceSelector:
    matchNames:
    - d8-{{ .Chart.Name }}
{{- end }}
