apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-configurator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-configurator
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - storage.deckhouse.io
    resources:
      - blockdevices
    verbs:
      - get
      - list
      - create
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-configurator
subjects:
  - kind: ServiceAccount
    name: storage-configurator
    namespace: d8-storage-configurator
roleRef:
  kind: ClusterRole
  name: storage-configurator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storage-configurator
spec:
  selector:
    matchLabels:
      app: storage-configurator
  template:
    metadata:
      labels:
        app: storage-configurator
    spec:
      imagePullSecrets:
        - name: fox-registry
      serviceAccountName: storage-configurator
      containers:
        - name: ubuntu-container
          image: registry.flant.com/deckhouse/storage-configurator:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
            seLinuxOptions:
              level: s0
              type: spc_t
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: host-device-dir
              mountPath: /dev/
            - name: host-sys-dir
              mountPath: /sys/
            - name: host-root
              mountPath: /host-root/
              mountPropagation: HostToContainer
      volumes:
        - name: host-device-dir
          hostPath:
            path: /dev
            type: ""
        - name: host-sys-dir
          hostPath:
            path: /sys/
            type: Directory
        - name: host-root
          hostPath:
            path: /