on:
  push:
    tags:
      - '**'

jobs:
  prod_ce_setup_build:
    runs-on: ubuntu-latest
    env:
      MODULES_REGISTRY: ${{ vars.PROD_REGISTRY }}
      CI_COMMIT_REF_NAME: ${{ github.ref_name }}
      MODULES_MODULE_NAME: ${{ vars.MODULE_NAME }}
      MODULES_MODULE_SOURCE: ${{ vars.PROD_CE_MODULE_SOURCE }}
      MODULES_REGISTRY_LOGIN: ${{ secrets.PROD_MODULES_REGISTRY_LOGIN }}
      MODULES_REGISTRY_PASSWORD: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      MODULES_MODULE_TAG: ${{ github.ref_name }}
    name: Build and Push images
    steps:
      - run: |
          echo $MODULES_REGISTRY
          echo $MODULES_MODULE_NAME
          echo $MODULES_MODULE_SOURCE
          echo $MODULES_MODULE_TAG
        shell: bash
        name: Show vars

      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v1
      - uses: deckhouse/modules-actions/build@v1

  prod_ee_setup_build:
    runs-on: ubuntu-latest
    env:
      MODULES_REGISTRY: ${{ vars.PROD_REGISTRY }}
      CI_COMMIT_REF_NAME: ${{ github.ref_name }}
      MODULES_MODULE_NAME: ${{ vars.MODULE_NAME }}
      MODULES_MODULE_SOURCE: ${{ vars.PROD_EE_MODULE_SOURCE }}
      MODULES_REGISTRY_LOGIN: ${{ secrets.PROD_MODULES_REGISTRY_LOGIN }}
      MODULES_REGISTRY_PASSWORD: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      MODULES_MODULE_TAG: ${{ github.ref_name }}
    name: Build and Push images
    steps:
      - run: |
          echo $MODULES_REGISTRY
          echo $MODULES_MODULE_NAME
          echo $MODULES_MODULE_SOURCE
          echo $MODULES_MODULE_TAG
        shell: bash
        name: Show vars

      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v1
      - uses: deckhouse/modules-actions/build@v1

  prod_fe_setup_build:
    runs-on: ubuntu-latest
    env:
      MODULES_REGISTRY: ${{ vars.PROD_REGISTRY }}
      CI_COMMIT_REF_NAME: ${{ github.ref_name }}
      MODULES_MODULE_NAME: ${{ vars.MODULE_NAME }}
      MODULES_MODULE_SOURCE: ${{ vars.PROD_FE_MODULE_SOURCE }}
      MODULES_REGISTRY_LOGIN: ${{ secrets.PROD_MODULES_REGISTRY_LOGIN }}
      MODULES_REGISTRY_PASSWORD: ${{ secrets.PROD_MODULES_REGISTRY_PASSWORD }}
      MODULES_MODULE_TAG: ${{ github.ref_name }}
    name: Build and Push images
    steps:
      - run: |
          echo $MODULES_REGISTRY
          echo $MODULES_MODULE_NAME
          echo $MODULES_MODULE_SOURCE
          echo $MODULES_MODULE_TAG
        shell: bash
        name: Show vars

      - uses: actions/checkout@v4
      - uses: deckhouse/modules-actions/setup@v1
      - uses: deckhouse/modules-actions/build@v1
