name: Deploy Dev

on:
  workflow_dispatch:
   inputs:
      version:
        description: "Select version"
        type: choice
        default: alpha
        options:
          - "alpha"
          - "beta"
          - "early-access"
          - "stable"
          - "rock-solid"

      tag:
        description: "Tag of the module, exapmle v1.21.1"
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
       MODULES_REGISTRY: ${{ vars.DEV_REGISTRY }}
       CI_COMMIT_REF_NAME: ${{ github.ref_name }}
       MODULES_MODULE_NAME: ${{ vars.MODULE_NAME }}
       MODULES_MODULE_SOURCE: ${{ vars.DEV_MODULE_SOURCE }}
       RELEASE_CHANNEL: ${{ github.event.inputs.version }}
       MODULES_MODULE_TAG: ${{ github.event.inputs.tag }}
    name: Build and Push images
    steps:
      - run: |
          echo $MODULES_REGISTRY
          echo $CI_COMMIT_REF_NAME
          echo $MODULES_MODULE_NAME
          echo $MODULES_MODULE_SOURCE
          echo $RELEASE_CHANNEL
          echo $MODULES_MODULE_TAG
        shell: bash
        name: Show vars

    
    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: deckhouse/modules-actions/setup@v1
    #   - uses: deckhouse/modules-actions/deploy@v1
