name: Trivy check for sub repos

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Trivy check for sub repos
    runs-on: [self-hosted, regular]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare sub repo
        run: |
          version=v`grep "version :=" images/agent/werf.inc.yaml | awk -F'"' '{ print $2}'`
          git clone --depth 1 --branch $version ${{ secrets.SOURCE_REPO }}/util-linux/util-linux.git ./util-linux
          git clone ${{ secrets.SOURCE_REPO }}/lvmteam/lvm2.git ./lvm2
          version=`grep "version :=" images/sds-utils-installer/werf.inc.yaml | awk -F'"' '{ print $2}'`
          cd ./lvm2
          git checkout $version 
          cd ..

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
